# Generated by Django 5.0.2 on 2024-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor_specialty',
            new_name='DoctorSpecialty',
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='main.equipment'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_blank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
