# Generated by Django 5.0.2 on 2024-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code_images/'),
        ),
    ]
